### ISSUE TITLE
Ready for "production" ?

### ISSUE THREAD

**Issue by lionpeloux** [moien007/TcpFramework#2]
Hello,

I'm looking for a small yet robust TCP client implementation and your's seems promising.

I am working on a Kuka robot. On the robot, there is a TCP server that can handles up to 8 connections. I can ask the server to read a robot variable (for instance `$DATE`) and it will return to me the variable content (for instance `$DATE = {CSEC 0, SEC 10, MIN 10, HOUR 12, DAY 23, MONTH 1, YEAR 2019}`. In the same manner I can ask the server to write to a variable on the robot system.

Through this simple system, I would like to achieve :

* stream a list of point coordinates to the robot
* pool cyclically and async (every 200ms) the state of a bunch of system variables (actual position, speed, ...) to have a realtime monitoring dashboard on my laptop. And push some alerts to my phone with push bullet API.

My concern is about robustness :

* I need to be able to respond to read/write errors or fails
* I need to detect when the network (through pin request) or the server is down / not reachable
* I need to be able to run a re-read / re-write / re-connection strategy when an error occurs

Do you think that your client library is yet ok for me to do that ?

Thank you for sharing your code though !

**Comment by moien007** [comment]
Currently, TcpFramework does not provide any TCP client API since I was focused only on high-performance TCP server implementation when developing this library. I have some plans for including a TCP client into this library in the future. But even now, I don't recommend this library for hosting a TCP server since it's not complete and untested. 

Regards.

**Comment by lionpeloux** [comment]
Ok, thank you for answering !
